services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    restart: on-failure:1
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./.env
    command: yarn run start:dev
